name: Auto Label Issues and Check PRs

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add NSoC label to issues
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const text = (issue.title + " " + (issue.body || "")).toLowerCase();

            if (text.includes("nsoc")) {
              console.log("NSoC detected ✅");

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ["NSoC'26"]
              });
            }

      - name: Check nsoc26 tag in PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const text = (pr.title + " " + (pr.body || "")).toLowerCase();

            const hasTag = text.includes("nsoc");

            if (!hasTag) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: "⚠️ **NSoC 2026**: This PR is missing the `nsoc26` tag.\n\nPlease update the PR title or description to include **`nsoc26`**.\n\nExample: `feat: add login page [nsoc26]`"
              });
            }
