name: Auto Label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add label if NSoC'26 found
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || "";
            const title = issue.title || "";

            if (body.includes("NSoC'26") || title.includes("NSoC'26")) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ["NSoC'26"]
              });
            }
